/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in a running project.
// It is committed here because the MVP source tree is created from scratch.
